services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - storage-data:/var/lib/outline/data

  redis:
    image: redis
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  storage-data:
  database-data: